import utils from '../../lib/utils'

export default utils.genNamespace('main', {
  getters: {
    lang: 1,
    sessionId: 1,
    user: 1,
    diffTs: 1,
    toast: 1,
    modal: 1,
    isLoading: 1,
    isMobile: 1,
    sidePanel: 1,
    modules: 1,
    selectedModule: 1,
    sideMenus: 1,
  },
  actions: {
    setLang: 1,
    setSession: 1,
    setServerTs: 1,
    setProfile: 1,
    showToast: 1,
    hideToast: 1,
    setModal: 1,
    setIsLoading: 1,
    setIsMobile: 1,
    setSidePanel: 1,
    toggleSidePanel: 1,
    setModules: 1,
    setSelectedModule: 1,
    setSideMenus: 1,
  },
  mutations: {
    setBaseTs: 1,
    setLang: 1,
    setSession: 1,
    setProfile: 1,
    setToast: 1,
    setModal: 1,
    setIsLoading: 1,
    setIsMobile: 1,
    setSidePanel: 1,
    toggleSidePanel: 1,
    setModules: 1,
    setSelectedModule: 1,
    setSideMenus: 1,
  },
})
