CREATE TABLE `answer` (
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`ts` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`form_id` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`ans` TEXT NOT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;
